config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"

  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :results, dependent: :destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :questions, through: :results
  has_many :results, dependent: :destroy
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :exams, dependent: :destroy
  belongs_to :category
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :answer
  belongs_to :exam
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :exams, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = I18n.t "static_page.title"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("static_page.about"), about_path %></li>
      <li><%= link_to t("static_page.news"), "#" %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("static_page.title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("static_page.home"), root_path %></li>
        <li><%= link_to t("static_page.help"), help_path %></li>
        <li><%= link_to t("static_page.log_in"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, t("static_page.about") %>

<h1><%= t("static_page.about_us") %></h1>
<p><%= t("static_page.intro_about") %></p>

app/views/static_pages/help.html.erb
<% provide :title, t("static_page.help") %>

<h1><%= t("static_page.help") %></h1>
<p><%= t("static_page.intro_help") %></p>

app/views/static_pages/home.html.erb
<% provide :title, t("static_page.home") %>

<div class="center jumbotron">
  <h1><%= t("static_page.intro_home") %></h1>
  <p><%= t("static_page.home_description") %></p>

  <%= link_to t("static_page.sign_up"), "#", class: "btn btn-primary" %>
</div>